site_name: Donkey Car
theme:
    name: 'material'
    language: 'ja'
extra:
    search:
        language: 'jp'

repo_url: https://github.com/coolerking/
edit_uri: edit/master/docs
extra_css:
    - extra.css

pages:
    - Home: index.md
    - User Guide:
        - 'Build a car.': guide/build_hardware.md
        - 'Install the software': guide/install_software.md
        - 'Get driving.': guide/get_driving.md
        - 'Calibrate steering and throttle.': guide/calibrate.md
        - 'Train an autopilot.': guide/train_autopilot.md
        - 'Donkey Simulator.': guide/simulator.md
    - Parts:
        - 'About': parts/about.md
        - 'Actuators': parts/actuators.md
        - 'Controllers': parts/controllers.md
        - 'Stores': parts/stores.md
        - 'IMU': parts/imu.md
    - Utilities:
        - 'donkey': utility/donkey.md
    - References:
        - 'stable-baselines': stable-baselines/blog.md
        - 'sixaxis': sixaxis.md
        - 'Wii-U': wii-u.md
        - 'Learn to drive in a Day': paper/Learn_to_Drive_in_a_Day.md
        - 'ver2.5.8': release2.5.8.md

    - Supported Cars: supported_cars.md
    - Roll Your Own: roll_your_own.md
    - Contribute : contribute.md
    - Tests : tests.md
    - Releases : release.md
    - FAQ : faq.md
